# Install project dependencies in small clusters and keep large caches on D: by default.
# Docker images and service containers are only pulled or started when explicitly requested.
[CmdletBinding()]
param(
    [ValidateSet('android', 'mobile', 'api', 'ai', 'data', 'identity', 'routing', 'all')]
    [string[]]$Cluster = @('mobile'),
    [switch]$AcceptAndroidLicenses,
    [switch]$PullImages,
    [switch]$StartServices
)

$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$sdkRoot = if ($env:ANDROID_HOME) { $env:ANDROID_HOME } else { 'D:\Android\Sdk' }
$cacheRoot = if ($env:COMMENCYS_CACHE_ROOT) { $env:COMMENCYS_CACHE_ROOT } else { 'D:\Commencys-Cache' }
$flutterCommand = Get-Command flutter -ErrorAction SilentlyContinue
$pythonCommand = Get-Command python -ErrorAction SilentlyContinue

# Stop the selected setup cluster on the first command that reports a failure.
function Invoke-Checked {
    param([string]$Program, [string[]]$Arguments)
    & $Program @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed with exit code ${LASTEXITCODE}: $Program $($Arguments -join ' ')"
    }
}

# Write machine-specific Flutter and Android SDK paths to the ignored local.properties file.
function Set-AndroidLocalConfiguration {
    if (-not (Test-Path -LiteralPath $sdkRoot)) {
        throw "Android SDK not found at $sdkRoot. Run the android cluster first."
    }
    if ($null -eq $flutterCommand) {
        throw 'Flutter was not found on PATH. Install Flutter 3.47.6 and reopen the shell.'
    }
    $flutterRoot = Split-Path (Split-Path $flutterCommand.Source -Parent) -Parent
    $sdkProperty = $sdkRoot.Replace('\', '\\')
    $flutterProperty = $flutterRoot.Replace('\', '\\')
    @(
        '# Machine-local SDK paths generated by tools/bootstrap.ps1; this file is ignored by Git.',
        '# sdk.dir selects the Android SDK installed for this workstation.',
        "sdk.dir=$sdkProperty",
        '# flutter.sdk selects the Flutter SDK used by the Android Gradle plugin.',
        "flutter.sdk=$flutterProperty"
    ) |
        Set-Content -LiteralPath (Join-Path $repoRoot 'android/local.properties') -Encoding ascii
}

# Download the pinned Google command-line tools and verify their archive checksum before use.
function Install-AndroidCommandLineTools {
    $sdkManager = Join-Path $sdkRoot 'cmdline-tools/latest/bin/sdkmanager.bat'
    if (Test-Path -LiteralPath $sdkManager) { return }

    $archivePath = Join-Path $env:TEMP 'commandlinetools-win-15859902_latest.zip'
    $extractPath = Join-Path $env:TEMP "android-command-line-tools-$PID"
    $downloadUrl = 'https://dl.google.com/android/repository/commandlinetools-win-15859902_latest.zip'
    $expectedHash = '90ae805d20434428bffcb699c290860f19bb5f66a67e6b330067e3de801fb04a'

    New-Item -ItemType Directory -Path $sdkRoot,$env:TEMP -Force | Out-Null
    Invoke-WebRequest -Uri $downloadUrl -OutFile $archivePath
    $actualHash = (Get-FileHash -LiteralPath $archivePath -Algorithm SHA256).Hash.ToLowerInvariant()
    if ($actualHash -ne $expectedHash) {
        throw 'Android Command-line Tools archive checksum did not match the published value.'
    }

    Expand-Archive -LiteralPath $archivePath -DestinationPath $extractPath -Force
    $targetDirectory = Join-Path $sdkRoot 'cmdline-tools/latest'
    if (Test-Path -LiteralPath $targetDirectory) {
        throw "A partial Android Command-line Tools directory already exists at $targetDirectory. Inspect it before retrying."
    }
    New-Item -ItemType Directory -Path $targetDirectory -Force | Out-Null
    Get-ChildItem -LiteralPath (Join-Path $extractPath 'cmdline-tools') |
        Move-Item -Destination $targetDirectory
}

# Configure the Android SDK under D:, install the project's declared packages, and optionally accept licenses.
function Install-AndroidCluster {
    $env:ANDROID_HOME = $sdkRoot
    $env:ANDROID_SDK_ROOT = $sdkRoot
    $env:ANDROID_USER_HOME = Join-Path $sdkRoot 'UserHome'
    $env:TEMP = Join-Path $sdkRoot 'Temp'
    $env:TMP = $env:TEMP
    New-Item -ItemType Directory -Path $env:TEMP -Force | Out-Null
    Install-AndroidCommandLineTools
    $sdkManager = Join-Path $sdkRoot 'cmdline-tools/latest/bin/sdkmanager.bat'
    if ($AcceptAndroidLicenses) {
        Invoke-Checked $flutterCommand.Source @('doctor', '--android-licenses')
    }
    $packages = Get-Content (Join-Path $PSScriptRoot 'android-sdk-packages.txt') |
        Where-Object { $_ -and -not $_.StartsWith('#') }
    Invoke-Checked $sdkManager (@("--sdk_root=$sdkRoot", '--install') + $packages)
    Set-AndroidLocalConfiguration
}

# Create the shared Python environment on D: and install the API or optional AI requirements.
function Install-PythonCluster {
    if ($null -eq $pythonCommand) { throw 'Python was not found on PATH.' }
    $env:TEMP = Join-Path $cacheRoot 'Temp'
    $env:TMP = $env:TEMP
    $env:PIP_CACHE_DIR = Join-Path $cacheRoot 'Pip'
    $env:HF_HOME = Join-Path $cacheRoot 'HuggingFace'
    $env:HUGGINGFACE_HUB_CACHE = Join-Path $env:HF_HOME 'hub'
    $env:TORCH_HOME = Join-Path $cacheRoot 'Torch'
    $venvPath = Join-Path $cacheRoot 'Python/commencys'
    $venvPython = Join-Path $venvPath 'Scripts/python.exe'
    New-Item -ItemType Directory -Path $env:TEMP,$env:PIP_CACHE_DIR,$env:HF_HOME,$env:HUGGINGFACE_HUB_CACHE,$env:TORCH_HOME -Force | Out-Null
    if (-not (Test-Path -LiteralPath $venvPython)) {
        New-Item -ItemType Directory -Path (Split-Path $venvPath -Parent) -Force | Out-Null
        Invoke-Checked $pythonCommand.Source @('-m', 'venv', $venvPath)
    }
    $requirements = if ($selectedCluster -eq 'ai') {
        'backend/requirements-ai.txt'
    } else {
        'backend/requirements-dev.txt'
    }
    Invoke-Checked $venvPython @('-m', 'pip', 'install', '-r', (Join-Path $repoRoot $requirements))
    Write-Host "Python environment: $venvPath"
}

# Configure Flutter's Pub/Gradle caches on D: and resolve the Flutter packages in pubspec.yaml.
function Install-MobileCluster {
    if ($null -eq $flutterCommand) { throw 'Flutter was not found on PATH.' }
    $env:PUB_CACHE = Join-Path $cacheRoot 'Pub'
    $env:GRADLE_USER_HOME = Join-Path $cacheRoot 'Gradle'
    $env:ANDROID_USER_HOME = Join-Path $sdkRoot 'UserHome'
    $env:TEMP = Join-Path $sdkRoot 'Temp'
    $env:TMP = $env:TEMP
    New-Item -ItemType Directory -Path $env:PUB_CACHE,$env:GRADLE_USER_HOME,$env:TEMP -Force | Out-Null
    Set-AndroidLocalConfiguration
    Push-Location $repoRoot
    try { Invoke-Checked $flutterCommand.Source @('pub', 'get') }
    finally { Pop-Location }
}

# Validate, pull, or start one optional Compose profile without starting unrelated services.
function Install-ComposeCluster {
    $dockerCommand = Get-Command docker -ErrorAction SilentlyContinue
    if ($null -eq $dockerCommand) { throw 'Docker-compatible CLI was not found.' }
    $env:OSRM_DATA_DIR = if ($env:OSRM_DATA_DIR) { $env:OSRM_DATA_DIR } else { Join-Path $cacheRoot 'OSRM/java' }
    $env:OSRM_DATA_DIR = $env:OSRM_DATA_DIR.Replace('\', '/')
    $env:POSTGRES_DB = if ($env:POSTGRES_DB) { $env:POSTGRES_DB } else { 'commencys' }
    $env:POSTGRES_USER = if ($env:POSTGRES_USER) { $env:POSTGRES_USER } else { 'commencys' }
    $env:POSTGRES_PASSWORD = if ($env:POSTGRES_PASSWORD) { $env:POSTGRES_PASSWORD } else { 'commencys-local-only' }
    $env:KC_BOOTSTRAP_ADMIN_USERNAME = if ($env:KC_BOOTSTRAP_ADMIN_USERNAME) { $env:KC_BOOTSTRAP_ADMIN_USERNAME } else { 'admin' }
    $env:KC_BOOTSTRAP_ADMIN_PASSWORD = if ($env:KC_BOOTSTRAP_ADMIN_PASSWORD) { $env:KC_BOOTSTRAP_ADMIN_PASSWORD } else { 'commencys-local-admin-only' }
    $profile = switch ($selectedCluster) {
        'data' { 'data' }
        'identity' { 'identity' }
        'routing' { 'routing' }
        default { throw 'Choose one Compose cluster: data, identity, or routing.' }
    }
    $composeArgs = @('compose', '--profile', $profile)
    Push-Location $repoRoot
    try {
        if ($StartServices) {
            if ($profile -eq 'routing' -and -not (Test-Path (Join-Path $env:OSRM_DATA_DIR 'java-latest.osrm'))) {
                throw 'Routing data is missing. Run tools/prepare-osrm.ps1 first; it downloads and prepares a large regional extract.'
            }
            Invoke-Checked $dockerCommand.Source ($composeArgs + @('up', '-d'))
        } elseif ($PullImages) {
            Invoke-Checked $dockerCommand.Source ($composeArgs + @('pull'))
        } else {
            Invoke-Checked $dockerCommand.Source ($composeArgs + @('config', '--quiet'))
            Write-Host "Compose profile '$profile' is configured. Pull or start it only after the container engine's storage is on D:."
        }
    }
    finally { Pop-Location }
}

if ($Cluster -contains 'all') {
    $selectedCluster = 'android'
    Install-AndroidCluster
    $selectedCluster = 'mobile'
    Install-MobileCluster
    $selectedCluster = 'api'
    Install-PythonCluster
    $selectedCluster = 'ai'
    Install-PythonCluster
    foreach ($serviceCluster in @('data', 'identity', 'routing')) {
        $selectedCluster = $serviceCluster
        Install-ComposeCluster
    }
    exit 0
}

foreach ($selectedCluster in $Cluster) {
    switch ($selectedCluster) {
        'android' { Install-AndroidCluster }
        'mobile' { Install-MobileCluster }
        'api' { Install-PythonCluster }
        'ai' { Install-PythonCluster }
        'data' { Install-ComposeCluster }
        'identity' { Install-ComposeCluster }
        'routing' { Install-ComposeCluster }
    }
}
